# This file is not properly setup yet!
# Do not use!
# temporary compile: g++ -std=c++11 test.cpp ../src/ast.cpp ../src/source.cpp ../src/lexer.cpp ../src/parser.cpp -o run


# SOURCEDIR = ../src
# BUILDDIR = ../build
# EXECUTABLE = Test
#
# SOURCES = $(wildcard ../src/*.cpp)
# OBJECTS = $(patsubst $(SOURCEDIR)/%.cpp,$(BUILDDIR)/%.o,$(SOURCES))
#
# CC = g++
# CFLAGS  = -c -g -Wall
#
#
# all: dir $(BUILDDIR)/$(EXECUTABLE)
#
# dir:
# 	mkdir -p $(BUILDDIR)
#
# $(BUILDDIR)/$(EXECUTABLE): $(OBJECTS)
# 	$(CC) -o $@ $^
#
# $(OBJECTS): $(BUILDDIR)/%.o : $(SOURCEDIR)/%.cpp
# 	$(CC) $(CFLAGS) -o $@ $<
#
# clean:
# 	rm -f $(BUILDDIR)/*o $(BUILDDIR)/$(EXECUTABLE)
